// Package trace turns a failing input into a test you can paste.
//
// A machine that fails prints the op sequence and the shrunk bytes,
// which is enough to understand the failure and not enough to work on
// it. The next step is always the same and always manual: get that
// input into a test that runs on its own, so it can be stepped through,
// instrumented, and kept as a regression case.
//
// [Repro] writes that test. The generated source replays the input
// through [fuzztape.Machine.Replay] and carries the decoded op sequence
// as a comment, so the file explains itself when someone opens it a
// month later.
//
// The output is gofmt'd Go, and it compiles: the package's own test
// builds and runs a generated file to keep that claim honest.
package trace

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

// Repro returns the source of a test that replays data against the
// machine named by machineExpr — any expression that evaluates to a
// [fuzztape.Machine] in the package the file will live in, such as
// "queueMachine" or "newMachine(false)".
//
// ops, if given, is the decoded op sequence from
// [fuzztape.Machine.Trace]; it is recorded as a comment so the input is
// legible without running it.
func Repro(testName, machineExpr string, data []byte, ops []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "func %s(t *testing.T) {\n", testName)
	if len(ops) == 0 {
		fmt.Fprintf(&b, "\t// %d bytes, decoding to no ops.\n", len(data))
	} else {
		fmt.Fprintf(&b, "\t// %d bytes, decoding to %d ops:\n", len(data), len(ops))
		for _, op := range ops {
			fmt.Fprintf(&b, "\t//\t%s\n", op)
		}
	}
	fmt.Fprintf(&b, "\tdata := []byte(%q)\n", data)
	fmt.Fprintf(&b, "\t%s.Replay(t, data)\n", machineExpr)
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		// Only reachable if machineExpr or testName is not valid Go,
		// which is the caller's error to see rather than one to hide.
		return b.String()
	}
	return string(src)
}

// File returns a complete, compilable test file: build tag free, one
// import, and the test [Repro] generates.
func File(pkg, testName, machineExpr string, data []byte, ops []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by fuzztape/trace. Edit freely: it is a\n")
	b.WriteString("// starting point for debugging, not a managed file.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"testing\"\n\n")
	b.WriteString(Repro(testName, machineExpr, data, ops))

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return b.String()
	}
	return string(src)
}

// Write saves the output of [File] to path.
func Write(path, pkg, testName, machineExpr string, data []byte, ops []string) error {
	return os.WriteFile(path, []byte(File(pkg, testName, machineExpr, data, ops)), 0o644)
}
