package runner

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const TipSchema = "go-iroh-tip/1"

// TipReport is advisory evidence against moving upstream main. It is not
// merged into the committed compatibility claim.
type TipReport struct {
	Schema           string    `json:"schema"`
	Generated        time.Time `json:"generated"`
	GoCommit         string    `json:"go_commit"`
	UpstreamCommit   string    `json:"upstream_commit"`
	UpstreamDescribe string    `json:"upstream_describe"`
	ExpectedPin      string    `json:"expected_pin"`
	Cells            []Cell    `json:"cells"`
}

func (r *TipReport) Validate() error {
	if r.Schema != TipSchema || r.GoCommit == "" || r.UpstreamCommit == "" || r.UpstreamDescribe == "" || r.ExpectedPin == "" {
		return errors.New("tip report provenance is incomplete")
	}
	for _, cell := range r.Cells {
		if err := cell.Validate(); err != nil {
			return err
		}
		if cell.Expected == "" {
			return fmt.Errorf("cell %s: expected verdict is missing", cell.Scenario)
		}
	}
	return nil
}

func (r *TipReport) Unexpected() error {
	return (&Report{Cells: r.Cells}).Unexpected()
}

func (r *TipReport) Write(jsonPath, markdownPath string) error {
	if err := r.Validate(); err != nil {
		return err
	}
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return fmt.Errorf("encode tip evidence: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(jsonPath), 0o755); err != nil {
		return fmt.Errorf("create tip evidence directory: %w", err)
	}
	if err := os.WriteFile(jsonPath, append(b, '\n'), 0o644); err != nil {
		return fmt.Errorf("write tip evidence: %w", err)
	}
	if err := os.WriteFile(markdownPath, r.Markdown(), 0o644); err != nil {
		return fmt.Errorf("write tip compatibility: %w", err)
	}
	return nil
}

func (r *TipReport) Markdown() []byte {
	var b strings.Builder
	b.WriteString("# Iroh tip wire-compatibility advisory\n\n")
	b.WriteString("> Advisory only. This report targets moving upstream `main`; it is not a compatibility claim about a released or pinned pre-release version.\n\n")
	fmt.Fprintf(&b, "Upstream tip: `%s` (`%.8s`). Generated by the nightly wire-drift canary against go-iroh commit `%s` at %s.\n\n", r.UpstreamDescribe, r.UpstreamCommit, r.GoCommit, r.Generated.Format(time.RFC3339))
	b.WriteString("## At a glance\n\n")
	fmt.Fprintf(&b, "| Scenario | Tier | Expected at pinned %s | tip (%s) | Evidence |\n", r.ExpectedPin, r.UpstreamDescribe)
	b.WriteString("|---|---|:---:|:---:|---|\n")
	for _, cell := range r.Cells {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", cell.Scenario, cell.Tier, cell.Expected, formatAdjudication(cell, 1), strings.TrimSuffix(cell.Detail, "."))
	}
	b.WriteString("\nAll other scenarios are `—` (untested) at tip. The nightly canary deliberately exercises only the bidirectional CustomAddr wire-vector suite; blocking CI runs the full pinned 1.0 matrix and the same focused suite at the 1.1-pre pin.\n")
	b.WriteString("\n## Peer\n\n| Ref | Rust peer | Source | SHA-256 digest |\n|---:|---|---|---|\n")
	if len(r.Cells) != 0 {
		cell := r.Cells[0]
		name := strings.SplitN(cell.Peer, "@", 2)[0]
		fmt.Fprintf(&b, "| [1] | %s | upstream-main@%.8s | `%s` |\n", name, r.UpstreamCommit, strings.TrimPrefix(cell.PeerDigest, "sha256:"))
	}
	b.WriteString("\nThe nightly workflow appends the **At a glance** section to the GitHub Actions job summary and uploads this Markdown file with its machine-readable evidence JSON.\n")
	return []byte(b.String())
}
